name: Install NPM Packages

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  install-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
          mode: "docker-intercept"
          debug: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or use your project's Node version

      - name: Install dependencies
        run: npm install --log-level=verbose
        env:
            CI: false
        
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
          
  gather_analytics:
      
   runs-on: ubuntu-latest
   name: Gather Analytics
   needs: install-deps
   if: always()
   steps:
   - name: Gather Status
     uses: invisirisk/pse-action@latest
     with:
      api_url: "https://app.invisirisk.com"
      app_token: ${{ secrets.IR_API_KEY }}
      send_job_status: "true"
      debug: "true"
